[project]
name = "coordinate-mapper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ruan-ds", email = "ruantmelon@icloud.com" }
]
requires-python = ">=3.11"
dependencies = [
    "pyside6>=6.11.1",
    "ruff>=0.16.1",
]

[project.scripts]
coordinate_mapper = "coordinate_mapper.main:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"